CREATE TABLE ROTA (
	ROTA_ID INT NOT NULL AUTO_INCREMENT,
	ROTA_NR_PONTO_ORIGEM INT NOT NULL,
	ROTA_NR_PONTO_DESTINO INT NOT NULL,
	ROTA_NR_DISTANCIA INT NOT NULL,
	MAPA_ID INT NOT NULL,
	CONSTRAINT PK_ROTA PRIMARY KEY(ROTA_ID),
	CONSTRAINT FK_MAPA_ROTA FOREIGN KEY(MAPA_ID) REFERENCES MAPA (MAPA_ID)
);