CREATE TABLE ROTA (
	ROTA_ID BIGINT NOT NULL AUTO_INCREMENT,
	ROTA_TX_PONTO_ORIGEM VARCHAR(30) NOT NULL,
	ROTA_TX_PONTO_DESTINO VARCHAR(30) NOT NULL,
	ROTA_NR_DISTANCIA FLOAT(14, 2) NOT NULL,
	MAPA_ID BIGINT NOT NULL,
	CONSTRAINT PK_ROTA PRIMARY KEY(ROTA_ID),
	CONSTRAINT FK_MAPA_ROTA FOREIGN KEY(MAPA_ID) REFERENCES MAPA (MAPA_ID)
);